project_id = "fihcubajfjjbcjqiqqrv"

[functions.scrape-news]
verify_jwt = false

[functions.clear-all-users]
verify_jwt = false

[functions.send-connection-notification]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false
