project_id = "fihcubajfjjbcjqiqqrv"

[functions.send-connection-notification]
verify_jwt = false

[functions.send-temp-password]
verify_jwt = false

[functions.reset-test-accounts]
verify_jwt = false
